backend:
  name: git-gateway
  branch: ocean
publish_mode: editorial_workflow
media_folder: data/media
collections:
  - name: stream
    label: stream
    folder: data/stream
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
slug:
  encoding: unicode
  clean_accents: true
